# Generated by Django 4.2.21 on 2025-05-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_data', '0002_measurements_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurements',
            name='height',
            field=models.FloatField(default=0),
        ),
    ]
