# Generated by Django 4.2.21 on 2025-05-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_data', '0004_measurements_biceps_measurements_calves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='calves',
            new_name='claves',
        ),
    ]
