# Generated by Django 4.2.21 on 2025-05-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_data', '0005_rename_calves_measurements_claves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='claves',
            new_name='calves',
        ),
        migrations.RenameField(
            model_name='measurements',
            old_name='sholders',
            new_name='shoulders',
        ),
    ]
