# Generated by Django 4.2.21 on 2025-05-29 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('body_data', '0006_rename_claves_measurements_calves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='date_add',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
